<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>voitures</title>
     <link rel="stylesheet" href="01-voiture.css">
</head>
<body>
    <header>
        <h1>Liste des voitures</h1>
     </header>
     <main>
         <?php foreach ($voitures as $index => $voiture) : ?>
        <article class="voiture">
            <h3> Numéro de la voiture <?= $voiture["id"] ?></h3>
            <hr>
            <div class="brand"> Marque <?= $voiture["brand"] ?></div>
            <div class="color"> Couleur <?= $voiture["color"] ?></div>
            <div class="kms"> Nombre de kms <?= $voiture["kms"] ?></div>
        </article>
        <?php endforeach ?>
    <main>
</body>
</html>