<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Produit</h1>
        <form action="09-confirmation.php" method="POST">
            <input type="number"  name="code" placeholder="votre code"></input>
            <input type="text"  name="name" placeholder="votre nom"></input>
            <input type="number"  name="price" placeholder="votre prix"></input>
            <textarea name="description" id="" cols="30" rows="10" placeholder="description"></textarea>
        <button type="submit">Envoi</button>
        </form>
    </header>
</body>
</html>