<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css"
    />
    <title>Document</title>
</head>
<body>
    <section class="hero is-warning">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
           liste des clients
          </h1>
        </div>
      </div>
    </section>
<section class="section">

<div class="container">
    <a href="05-customer-form.php" class="button is-warning is-pulled-right">Nouveau client</a>
<table class="table is-fullwidth table is-striped">
    <thead>
    <tr>
        <th>Numero</th>
        <th>Raison sociale</th>
        <th>Contact commercial</th>
        <th>Telephone</th>
        <th>Ville</th>
        <th>Pays</th>
        <th>Representant</th>
    </tr>
    <thead>
        <tbody>
            <?php foreach ($customers as $customer) : ?>
            <tr>
                <td><?= $customer['customerNumber'] ?></td>
                <td><?= $customer['customerName'] ?></td>
                <td><?= $customer['contactFirstName'] ?><?= $customer['contactLastName'] ?></td>
                <td><?= $customer['phone'] ?></td>
                <td><?= $customer['city'] ?></td>
                <td><?= $customer['country'] ?></td>
                <td><?= $customer['firstName'] ?> <?= $customer['lastName'] ?></td>
            </tr>
              <?php endforeach ?>
        </tbody>
</table>
</div>
</section>
    
</body>
</html>