<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css"
    />
  </head>
  <body>
    <section class="hero is-warning">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            Formulaire d'inscription
          </h1>
          <h2 class="subtitle">
            Remplissez le formulaire ci-dessus
          </h2>
        </div>
      </div>
    </section>
    <main>
      <section class="section">
        <div class="container">
             <?php if ($hasErrors == true) : ?>
            <div class="notification is-danger content">
                <h3 class="subtitle">
                    Erreur sur le formulaire :
                </h3>
                <ul>
                    <?php foreach ($errors as $error) : ?>
                    <li><?= $error ?></li>
                    <?php endforeach ?>
                    
                </ul>
            </div>
            <?php endif ?>
          <form action="10-confirmation.php" method="POST">
            <div class="field">
              <label for="" class="label">Prénom : </label>
              <div class="control">
                <input
                  type="text"
                  name="firstName"
                  class="input"
                  placeholder="Votre prenom"
                />
              </div>
            </div>
            <div class="field">
              <label for="" class="label">Nom :</label>
              <div class="control">
                <input
                  type="text"
                  name="lastName"
                  class="input"
                  placeholder="Votre nom de famille"
                />
              </div>
            </div>
            <div class="field">
              <label for="" class="label">Email</label>
              <div class="control">
                <input
                  type="text"
                  name="email"
                  class="input"
                  placeholder="Votre adresse email"
                />
              </div>
            </div>
            <div class="field">
                <label for="" class="label">Comment nous avez-vous connu ?</label>
                <div class="control">
                    <div class="select is-fullwidth">
                     <select name="origin" id="">
                    <?php foreach ($origins as $cle => $valeur) : ?>
                    <option value="<?= $cle ?>"><?= $valeur ?></option>
                    <?php endforeach ?>
                    </select>
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="control"></div>
                <button type="submit" class="button is-warning">
                  Je m'inscris !
                </button>
              </div>
            </div>
          </form>
        </div>
      </section>
    </main>
  </body>
</html>
