
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Loterie</title>
</head>
<body>
    <header>
     <h1>Loterie 3wa</h1>
    </header>
    <main>
        <ul>
            <?php foreach ($nombres as $valeur) : ?>
            <li><?php echo ($valeur) ?></li>
            <?php endforeach ?>
</ul>
    </main>
    
</body>
</html>


