

<form action="save-user.php" method="POST">
 <legend>Ajouter un utilisateur</legend>
 <label for="">email</label>
<input type="text" name="email">
<label for="">firstname</label>
<input type="text" name="firstname">
<label for="">lastname</label>
<input type="text"name="lastname">
<label for="">password</label>
<input type="password" name="password">
<button type="submit">Envoi</button>

</form>