<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link
      href="https://fonts.googleapis.com/css?family=Anton|Chonburi|Open+Sans"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/reset.css" />
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
    <header>
      <h1><i class="fas fa-book-open"></i> Blog</h1>
      <nav>
        <a href="index.php"><i class="fas fa-paper-plane"></i> Accueil</a>
        <a href="add-article.php"><i class="fas fa-edit"></i>Ecrire </a>
        <?php if (!isConnected()) : ?>
        <a href="form-login.php"><i class="fas fa-desktop"></i> Connexion</a>
        <a href="add-user.php"><i class="fas fa-file-alt"></i> Inscription</a>
      <?php else : ?>
        <a href="logout.php"><i class="fas fa-desktop"></i> Deconnexion(<?= $_SESSION['prenom'] ?>)</a>
         <?php endif ?>
        
        <a href="users.php"><i class="fas fa-file-alt"></i> utilisateurs</a>
      </nav>
    </header>
    <main>

