

    <table>
        <thead>
            <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Password</th>
             <th colspan="3">Modifications</th>
            </tr>
        </thead>
        <tbody>
             <?php foreach ($users as $user) : ?>
            <tr>
               
                <td><?= $user['id'] ?></td>
                 <td><?= $user['email'] ?></td>
                 <td><?= $user['firstname'] ?></td>
                 <td><?= $user['lastname'] ?></td>
                 <td><?= $user['password'] ?></td>
                <td><a href="add-user.php?id=<?= $user['id'] ?>" class="mod">Ajouter</a></td>
                 <td><a href="edit-user.php?id=<?= $user['id'] ?>" class="mod">Modifier</a></td>
                 <td><a href="delete-user.php?id=<?= $user['id'] ?>" class="mod">Supprimer</a></td>
            </tr>
             <?php endforeach ?>
        </tbody>
    </table>
    