<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Liste des produits</h1>
    </header>
    <main>
    <?php foreach ($products as $index => $product) : ?>
    <article class="product">
        <p>Product name :</p>
        <p class="productName"> <?= $product["productName"] ?></p>
        <p class="productLine"> product name :<?= $product["productLine"] ?></p>
    </article>
    <?php endforeach ?>
</main>
</body>
</html>