<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>
    Votre commande est envoyée
    </h1>
    <h2>
        Voici les informations soumises
    </h2>
    <ul>
        <li><?= $title ?></li>
        <li><?= $price ?></li>
        <li><?= $description ?></li>
        <li><?= $vegetarian ?></li>
    </ul>
    
</body>
</html>