<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>Bonjour <?= $nom = $_POST["nom"], ?> </h2>
    <form action="" method="POST"> 
        <ul> 
            <li><input type="text" name="nom" > Nom</li>
        <li><input type="text" name="prenom">Prenom</li>
        <li><input type="text" name="mail">Mail</li>
       <li> <input type="text" name="telephone">Telephone</li>
        <li><button type="submit">Envoyer</button></li>

        </ul>
    </form>
</body>
</html>
