<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Products</h1>
    </header>
<main>
   
    <table border='1'>
        <tr>
            <th>ref</th>
            <th>quantité</th>
            <th>prix unitaire</th>
            <th>Total</th>
        </tr>
        <?php foreach ($products as $index => $product) : ?>
        <tr>
            <td><?= $product['productCode'] ?></td>
            <td><?= $product['quantityOrdered'] ?></td>
            <td><?= $product['priceEach'] ?></td>
            <td><?= $product['TOTAL'] ?></td>
        </tr>
        <?php endforeach ?>
    </table>
</main>
</body>
</html>