<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="03-style.css">
</head>
<body>
    <header>
        <h1>Vendors</h1>
    </header>
    <main>
        <?php foreach ($vendors as $index => $vendor) : ?>
        <article class="vendor">
            <p class="titre">Nom du fournisseur</p>
            <p class="fournisseur"><?= $vendor['fournisseur'] ?></p>
            <p class="titre">Moyenne</p>
            <p class="moyenne"><?= $vendor['moyenne'] ?></p>
            <p class="titre">Moyenne maximum</p>
            <p class="maximum"><?= $vendor['maximum'] ?></p>
             <p class="titre">Moyenne minimum</p>
            <p class="minimum"><?= $vendor['minimum'] ?></p>
        </article>
         <?php endforeach ?>
    </main>
</body>
</html>