
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Bonjour<?= $prenom ?></h1>
        <?php if ($age != 0) : ?>
            <p>
                Vous avez <?= $age ?> ans, vous êtes donc un
                <?php if ($age >= 18) : ?>
                    adulte
                <?php else : ?>
                    enfant
                <?php endif ?>
            </p>
        <?php endif ?>
    </header>
</body>
</html>