<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>
            <?php if ($isSubmitted) : ?>
            votre cours a bien été ajouté
        <?php else : ?>
        il y a eu une erreur
        <?php endif ?>
        </h1>
        <main>
            <?php if ($isSubmitted) : ?>
                <p> votre cours a bien été posté le titre est <?= $title ?></p>
                <p>la description est <?= $description ?> </p>
                <p> Le professeur est <?= $teacher ?></p>
                <p> la durée est  <?= $duration ?></p>
                <?php else : ?>
                <p> vous n'avez rien à faire là c'est une erreur</p>
                <a href="08-cours.php"> retour au formulaire </a>
                <?php endif ?>

        </main>
    
</body>
</html>