<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <header><h1>Liste des cours</h1></header>
    <main>
        <form action="08-confirmation.php" method="POST">
        <input type="text" name="title" placeholder="title">
        <textarea name="description" placeholder="description"></textarea>
        <input type="text" name="teacher" placeholder="teacher">
         <input type="number" name="duration" placeholder="1">
         <button type="submit">Envoi</button>
         </form>
    </main>
</body>
</html>