<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" />
    <title>Détail de la commande 10 100</title>
</head>
<body>
    <section class="hero is-info">
        <div class="hero-body">
            <div class="container">
            <h1 class="title">
              Détail de la commande 10100
            </h1>
            <h2 class="subtitle">
              Commande pasée le 2003-01-21 par "Toy'r US"
            </h2>
            </div>
        </div>
</section>
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column" is-4>
                <article class="box">
                    <h2 class="subtitle">
                        Détail du client
                    </h2>
                    <strong>Nom : Toy's R us</strong> <br>
                    <strong>Contact : </strong>
                    Joseph Watson <br>
                    <strong>Représentant commercial : </strong> 
                    Lior Chamla<br>
                    <strong>Bureau </strong>  Marseille
                </article>
            </div>
            <div class="column">
                <article class="box">
                 <h2 class="subtitle">Détail de la commande</h2>   
                 <table class="table is-hoverable is-fullwidth is-bordered">
                 <thead>
                     <tr>
                         <th>Code</th>
                         <th>Nom</th>
                         <th>Quantité</th>
                         <th>Prix unitaire</th>
                         <th>Montant total</th>
                     </tr>
                 </thead>
                 <tbody>
                     <tr>
                         <td>SU 2942</td>
                         <td>1965 Mercedes</td>
                         <td>20</td>
                         <td>15 €</td>
                         <td>300 €</td>
                     </tr>
                       <tr>
                         <td>SU 2942</td>
                         <td>1965 Mercedes</td>
                         <td>20</td>
                         <td>15 €</td>
                         <td>300 €</td>
                     </tr>
                       <tr>
                         <td>SU 2942</td>
                         <td>1965 Mercedes</td>
                         <td>20</td>
                         <td>15 €</td>
                         <td>300 €</td>
                     </tr>
                 </tbody>
                 <tfoot>
                     <tr>
                         <td colspan = "4" class="has-text-weight-bold has-text-right">Total</td>
                         <td> 5500 €</td>
                     </tr>
                 </tfoot>
                </table>
                 </article>
                <a href="index.php" class="button is-link">Retour a la liste</a>
            </div>
        </div>
    </div>
</body>
</html>
