<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" />
    <title>Liste des commandes</title>
</head>
<body>
    <section class="hero is-info">
        <div class="hero-body">
            <div class="container">
            <h1 class="title">
                Primary title
            </h1>
            <h2 class="subtitle">
              Cher patron voici la liste de vos produits
            </h2>
            </div>
        </div>
</section>
<section class="section>">
    <table class="table is-fullwidth is-hoverable is-striped">
        <thead>
        <tr>
            <th>Numero</th>
            <th>Date de commande</th>
            <th>Date d'expedition</th>
            <th>Statut</th>
            <th>CLient</th>
            <th>Commercial</th>
            <th>Montant</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td><a href="orderdetails.php">10100</td>
                <td>2003-01-21</td>
                <td>2003-01-23</td>
                <td>Shipped</td>
                <td>Toy'R'us</td>
                <td>Steve Patterson</td>
                <td>54 000 €</td>
            </tr>
            <tr>
                <td><a href="orderdetails.php">10100</td>
                <td>2003-01-21</td>
                <td>2003-01-23</td>
                <td>Shipped</td>
                <td>Toy'R'us</td>
                <td>Steve Patterson</td>
                <td><54 000</td>
            </tr>
            <tr>
                <td><a href="orderdetails.php">10100</td>
                <td>2003-01-21</td>
                <td>2003-01-23</td>
                <td>Shipped</td>
                <td>Toy'R'us</td>
                <td>Steve Patterson</td>
                <td><54 000</td>
            </tr>
        </tbody>
    </table>
</section>
</body>
</html>