<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" />
    <title>Liste des commandes</title>
</head>
<body>
    <section class="hero is-info">
        <div class="hero-body">
            <div class="container">
            <h1 class="title">
                Primary title
            </h1>
            <h2 class="subtitle">
              Cher patron voici la liste de vos produits
            </h2>
            </div>
        </div>
</section>
<section class="section>">
    <table class="table is-fullwidth is-hoverable is-striped">
        <thead>
        <tr>
            <th>Numero</th>
            <th>Date de commande</th>
            <th>Date d'expedition</th>
            <th>Statut</th>
            <th>Client</th>
            <th>Commercial</th>
            <th>Montant</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($commandes as $index => $command) : ?>
            <tr>
                <td><a href="orderdetails.php?numero=<?= $command['orderNumber'] ?>"><?= $command['orderNumber'] ?></td>
                <td><?= $command['orderDate'] ?></td>
                <td><?= $command['shippedDate'] ?> </td>
                <td><?= $command['status'] ?></td>
                <td><?= $command['customerName'] ?></td>
                <td><?= $command['firstName'] ?> <?= $command['lastName'] ?></td>
                <td><?= $command['montant'] ?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</section>
</body>
</html>